# Generated by Django 3.0.6 on 2020-06-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quistion_text',
            new_name='question_text',
        ),
    ]
